export const GET_POKEMONS= "GET_POKEMONS";
export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const CREATE_POKEMON = "CREATE_POKEMON";
export const GET_TYPES= "GET_TYPES";
export const SORT_POKEMONS= "SORT_POKEMONS";